site_name: 'ATLAS Platform Documentation Portal'
site_description: 'F1-grade engineering telemetry tooling'
docs_dir: 'docs'
site_url: https://docs.atlas.mclarenapplied.com/

theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'indigo'
  custom_dir: overrides
  # assets/swoosh is cached aggressively - rename if icons change
  favicon:    'assets/swoosh/favicon.png'
  logo:       'assets/swoosh/logo.png'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - toc.integrate

copyright: Copyright &copy; 2021 McLaren Applied Ltd.

nav:
  - Home: index.md
  - News:
    - news/index.md
    - Release Notes:
      - news/release-notes/2021-R3.md
  - Quick-Reference:
    - quick-reference/keyboard-shortcuts.md
    - quick-reference/mouse.md
    - quick-reference/session-identifier-macros.md
    - Functions:
        - FDL Operators:            quick-reference/functions/fdl-operators.md
        - Processors:               quick-reference/functions/processors.md
        - DLLs:                     quick-reference/functions/dlls.md
  - Developer Info:
    - development/index.md
    - NuGet:
      - Packages:                   development/nuget/index.md
      - Feed Setup:                 development/nuget/setup.md
    - Guides:
      - Reading &amp; Writing Data: development/guides/data.md
      - Creating Custom Displays:   development/guides/displays.md
  - System Integration:
    - integration/rta.md
  - Downloads:
    - downloads/index.md
  - Support:
    - support/zendesk.md
    - support/sysreqs.md
  
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - toc:
      permalink: "#"
  - meta
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
