site_name: 'ATLAS Platform Documentation Portal'
site_description: 'F1-grade engineering telemetry tooling'
docs_dir: 'docs'
site_url: https://docs.atlas.mclarenapplied.com/

theme:
  name: 'material'
  palette:
    primary: 'grey'
    accent: 'indigo'
  custom_dir: overrides
  # assets/swoosh is cached aggressively - rename if icons change
  favicon:    'assets/swoosh/favicon.png'
  logo:       'assets/swoosh/logo.png'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - toc.integrate

copyright: Copyright &copy; 2021 McLaren Applied Ltd.

nav:
  - Home: index.md
  - News:
    - news/index.md
  - User Guide:
    - Index: manual/index.md
    - Articles:
      - manual/articles/scatterplot-sample-modes.md
    - User Interface:
      - manual/ui/keyboard.md
      - manual/ui/mouse.md
    - Recording:
      - manual/recording/session-identifier-macros.md
    - Functions:
        - FDL Operators:            manual/functions/fdl-operators.md
        - Processors:               manual/functions/processors.md
        - DLLs:                     manual/functions/dlls.md
    - ECU Bridge:
      - Design Concept:                   manual/ecu-bridge/design-concept.md
      - Introduction:
          - Architecture Overview:        manual/ecu-bridge/introduction.md
          - Dependencies Service:         manual/ecu-bridge/dependencies-service.md
          - Message Broker:
              - Apache Kafka:             manual/ecu-bridge/apache-kafka.md
              - Topic Management Service: manual/ecu-bridge/topic-management-service.md
          - ATLAS Visualisation:          manual/ecu-bridge/atlas-visualisation.md
          - Licensing:                    manual/ecu-bridge/licensing.md
      - Configuration:                    manual/ecu-bridge/configuration.md
  - Developer Guide:
    - developer/index.md
    - NuGet:
      - Packages:                   developer/nuget/index.md
      - Feed Setup:                 developer/nuget/setup.md
    - SQL Race API:                 developer/sqlrace-api.md
    - 📘 ATLAS Display API:         developer/atlas-displayapi.md
    - ECu Bridge:
        - Concepts:             
            - Topic, Streams & Sessions:           developer/ecu-bridge/concepts/topic-streams-sessions.md
            - It's all about Time:                 developer/ecu-bridge/concepts/its-all-about-time.md
            - Data feeds, formats & Views:         developer/ecu-bridge/concepts/data-feeds-formats-views.md      
            - ATLAS Configuration:                 developer/ecu-bridge/concepts/atlas-config.md 
        - Specifications:
            - Streaming Protocol:   developer/ecu-bridge/specifications/streaming-protocol.md
            - Protobuf Extensions:  developer/ecu-bridge/specifications/protobuf-extension.md
        - Code Samples (C&#35;):             
            - Intro:                developer/ecu-bridge/csharp/README.md
            - Read:                 developer/ecu-bridge/csharp/read.md
            - Write:                developer/ecu-bridge/csharp/write.md
            - Model Execution:      developer/ecu-bridge/csharp/model.md
            - Advanced Samples:     developer/ecu-bridge/csharp/advanced.md
  - 📙 Integration Guide:           integration/index.md
  - Downloads:
    - downloads/index.md
  - Support:
    - support/zendesk.md
    - support/sysreqs.md
  
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - toc:
      permalink: "#"
  - meta
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
